---
- block:
  - apt: update_cache=yes
  - apt: name={{item}} state=present
    with_items:
      - vim
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  become: yes
  become_method: sudo
- block:
  - yum: name={{item}} state=latest
    with_items:
      - vim
  become: yes
  become_method: sudo
  when: ansible_distribution == "CentOS"
